apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Broker
metadata:
  name: {{ default "s3" .Values.BrokerResourceName | quote }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-broker-resource"
spec:
  url: http://{{ .Release.Name }}-broker-server:{{.Values.CfBrokerPort}}
  authSecret:
     name: "{{ .Release.Name }}-broker-auth"
     namespace: "{{.Release.Namespace}}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-broker-auth"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-broker-resource"
data:
  username: {{ .Values.CfBrokerUsername | b64enc | quote }}
  password: {{ .Values.CfBrokerPassword | b64enc | quote }}
